# Generated by Djan 5.1.7 on 2025-04-06 14:29

import djan.db.models.deletion
from djan.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_employee_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Japan', 'Japan'), ('China', 'China'), ('Russia', 'Russia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finanace', 'FINANCE')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Country',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(default=None, on_delete=djan.db.models.deletion.CASCADE, to='crudapp.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDept',
            field=models.ForeignKey(default='', on_delete=djan.db.models.deletion.CASCADE, to='crudapp.department'),
            preserve_default=False,
        ),
    ]
