# Generated by Djan 5.1.7 on 2025-04-06 15:16

import djan.db.models.deletion
from djan.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_country_department_remove_employee_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(default=None, on_delete=djan.db.models.deletion.PROTECT, to='crudapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=djan.db.models.deletion.PROTECT, to='crudapp.city')),
                ('country', models.ForeignKey(default=None, on_delete=djan.db.models.deletion.PROTECT, to='crudapp.country')),
                ('state', models.ForeignKey(default=None, on_delete=djan.db.models.deletion.PROTECT, to='crudapp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=None, on_delete=djan.db.models.deletion.PROTECT, to='crudapp.state'),
        ),
    ]
